version: '3.1'

services:

  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  #fhirResourceManagerWebApp:
  #  image: fhir-resource-manager-web-app:1.0
  #  ports:
  #    - 8080:8080

